[build]
  command = "npm run build"
  publish = "client/build"
  
[functions]
  directory = "server/functions"

[dev]
  command = "npm start --prefix client"
  targetPort = 3000
  publish = "client/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 